name: Build lwjgl3

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with CI build script
      run: ./ci_build.bash

    - name: Upload modules release output
      uses: actions/upload-artifact@v1
      with:
        name: lwjgl3-modules
        path: bin/RELEASE

    - name: Upload native build output
      uses: actions/upload-artifact@v1
      with:
        name: lwjgl3-android-natives
        path: android_build/libs

    - name: Upload debug native build output
      uses: actions/upload-artifact@v1
      with:
        name: lwjgl3-debug-android-natives
        path: android_build/libs_debug
